version: '3.9'
services:
  shortener:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: shortener_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - postgresdb
    networks:
      - learning
    restart: on-failure

  postgresdb:
    image: postgres:alpine
    container_name: postgresdb_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: # Adds DDL to postgres container
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - learning
    restart: on-failure

networks:
  learning:
    driver: bridge